### PR TITLE
Add visible permissions check for widgets

### PR DESCRIPTION
**Pull request by howdu**
Add the ability to hide widgets using the `canView` method.

### CODE REVIEW

**Comment by howdu** [comment]
Just noticed you recommend setting the `canView` to false. In our use case we manually register the Livewire components used in tabs so that it doesn't get picked up by Filament.

**Comment by Jehizkia** [comment]
@howdu  Ah, I see. That's also a good option! Just out of curiosity, after you've registered the Livewire component, how do you use it in the tabs?

And Thanks btw!

**Review by Jehizkia — APPROVED** [review]
👌

**Comment by howdu** [comment]
Nothing special Livewire handles all the magic :) I register the widget in the service container
```php
Livewire::component('latest-products-widget', LatestProductsWidget::class);
```

Then use the class in your widgets array
```php
public array $widgets = [
   LatestProductsWidget::class,
];
```

**Comment by Jehizkia** [comment]
Gotcha! Thanks for the explanation 💪

**Pull request merged**
